### ISSUE TITLE
[Bug] chrome web store ，input box

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src.next#191]
In the chrome web store, after typing in the input box, click the first suggestion, and the selected one is indeed the last one. This is the case in all cases.
![qq_pic_merged_1627265221989](https://user-images.githubusercontent.com/55195642/126923608-00a88ea7-885b-4bde-b8d6-46cd040b68ae.jpg)
![qq_pic_merged_1627265179176](https://user-images.githubusercontent.com/55195642/126923610-11389270-f6c1-4a4a-8d4d-3b3987ed359d.jpg)

**Comment by cyfung1031** [comment]
It is possibly because you have the bottom address bar, see #89

**Comment by kiwibrowser** [comment]
It's fixed in last build

**Comment by drc5521** [comment]
> It's fixed in last build

Unfortunately, this problem has not been fixed in Generation 1074882115. Please watch the video.

https://user-images.githubusercontent.com/55195642/127329989-ca6fb010-2e30-4577-80d5-5f6a4f2a4eda.mp4

**Comment by kiwibrowser** [comment]
I can reproduce the issue on stable Chrome so it's a JS or CSS issue on their website. Which means we need a custom patch injected in their layout

@d3ward maybe if you have idea

**Comment by karl-pae** [comment]
This is probably the website issue. Tried in chrome, Samsung & Edge. Each have same issue.

**Comment by Lartsch** [comment]
Ridiculous that Google has still not made their Chrome Webstore mobile friendly. Yikes.

**Comment by d3ward** [comment]
It's funny because they have tablet support with touch events ( seems to be the one that make the selection of search result bugged )

> Ridiculous that Google has still not made their Chrome Webstore mobile friendly. Yikes.
